### ISSUE TITLE
Very weird issue (using "run()" vs. "runAndPrint()")

### ISSUE THREAD

**Issue by tanmayb123** [kareman/SwiftShell#19] opened 2016-05-14 05:54 UTC
I'm encountering a very weird issue here:

I'm using SwiftShell2, and when I do this:
`
let res = run("python", "ngrammine.py", "source.txt", "destination.txt"); print(res)
`
The app hangs. Completely. Just frozen.

However, when I do this:
`
runAndPrint("python", "ngrammine.py", "source.txt", "destination.txt")
`
It prints the result, and stops the app.

Why does the app hang in the former example?

**Comment by kareman** [comment] 2016-05-15 01:17
Hmm, could the Python script be exiting without closing its standard output (though I'm pretty sure Python does that automatically)? Currently the “run” function reads the output from the command before it is finished to work around issue #15.

Can you try branch "Issue-19-run-hangs" and see if that fixes the problem? And if it doesn't, would it be possible to send me the Python script so I could try to replicate the problem?

**Comment by tanmayb123** [comment] 2016-05-15 02:24
Sure, I'll try it out in a little bit, and get back to you. Thanks!

For now, though, I've worked-around by running "runAndPrint", then have Python save the output to a text file, and read the text file (though I don't intend for this to be a permanent solution)

**Comment by kareman** [comment] 2016-05-15 02:36
How about “runAsync”, does it hang too?

Could you try both

```
let res = runAsync("python", "ngrammine.py", "source.txt", "destination.txt").stdout.read()
```

and

```
let res = try runAsync("python", "ngrammine.py", "source.txt", "destination.txt").finish().stdout.read()
```

**Comment by tanmayb123** [comment] 2016-05-17 06:56
Hi, sorry, I was *very* busy for a few days, and am about to be for the next few days as well. However, while trying to install SwiftShell, I get #20?

**Comment by kareman** [comment] 2016-05-18 22:56
Are you still having the problem in #20? I can't reproduce it.

**Comment by kareman** [comment] 2016-06-06 14:42
It's been a while since the last update so I'm closing this issue. Feel free to open it again if the problem is still there.

**Closed by kareman** 2016-06-06 14:42 UTC
